### ISSUE TITLE
Web Connection Keep Listening

### ISSUE THREAD

**Issue by irkri** [PiMaV/BLITZ#29]
Once a web connection is established, keep it open until manually closed by the user (e.g. at button press).
This way, not only one image can be sent by the server.

**Comment by irkri** [comment]
This should now work. There is one thread that connects and keeps listening for incoming images.
The images get downloaded by another thread.

There might be a problem if the download takes too long and meanwhile a new message gets sent. Might not be worth fixing for now.

**Comment by PiMaV** [comment]
i've added this to General Performance

**Comment by PiMaV** [comment]
Needs to be checked

**Comment by PiMaV** [comment]
Ive tried WOLKE <-> BLITZ heavily.
No issues
Guess we can close this now
