### ISSUE TITLE
Web Connectivity

### ISSUE THREAD

**Issue by PiMaV** [PiMaV/BLITZ#31]
Sometimes im running into

 [NET] No such file available, aborting

issues, from out of nowhere.
Docker logs for wolke shows no error.
Maybe more info on client side "Filename" and such to debug properly

**Comment by irkri** [comment]
This happens if the address of the image we want to download is not correct. Either the image name or the address is wrong.
The address always is something like `https://x.x.x.x:<port>/<token>/filename=<filename>`.
I added the filename to the error message.

**Comment by PiMaV** [comment]
we have probably a problem with the filename. attached is the log file.
Some files work; others do not. The image is shown in WOLKE; thus its there.
But somewaht its not shown in BLITZ

Could it be a filename issue?
Furhtermore:
The name of the file in the lower task bar is shown as "cache.npy-0" for the last valid file.


Log file:

> [NET] No such file found at server: Spalt-1mm_2021-07-14_O2env-0p1Proz_Volt-10kV_Freq-10kHz_HVpw-1us_Flanke-SF_N2-299sccm_O2-0p3sccm_NrImages-25_Entl-EE_t0-0ns_Gate-500ns_Gain-200_MFIIc_Uvar.npy
> ------Dataset-------
  |8bit         False|
  |grayscale     True|
  |max. RAM       1.0|
  |Size-ratio     1.0|
  |Subset-ratio   1.0|
  |Size (MB)    8.105|
  --------------------
> [NET] Attempting to connect...
> [NET] Listening to incoming data
> [NET] Connected to server
> [NET] Attempting to connect...
> [NET] Listening to incoming data
> [NET] Connected to server
> [NET] Connected to server
> ------Dataset-------
  |8bit         False|
  |grayscale     True|
  |max. RAM       1.0|
  |Size-ratio     1.0|
  |Subset-ratio   1.0|
  |Size (MB)    7.812|
  --------------------
> [NET] No such file found at server: Spalt-1mm_2020-12-15_O2env-0p1Proz_Volt-10kV_Freq-10kHz_HVpw-1us_Flanke-SF_N2-299sccm_O2-0p3sccm_NrImages-25_Entl-EE_t0-0ns_Gate-500ns_Gain-200_MFIIc_fvar.npy
> [NET] No such file found at server: Spalt-0p5mm_2020-08-13_O2env-0p1Proz_Volt-8kV_Freq-10kHz_HVpw-1us_Flanke-SF_N2-299sccm_O2-0p3sccm_NrImages-25_Entl-EE_t0-0ns_Gate-250ns_Gain-200.npy
> [NET] No such file found at server: Spalt-0p5mm_2020-08-31_O2env-2Proz_Volt-8kV_Freq-10kHz_HVpw-1us_Flanke-SF_N2-294sccm_O2-6sccm_NrImages-25_Entl-x_Akku-1000_t0-0ns_Gate-250ns_Gain-0.npy
> ------Dataset-------
  |8bit         False|
  |grayscale     True|
  |max. RAM       1.0|
  |Size-ratio     1.0|
  |Subset-ratio   1.0|
  |Size (MB)    0.320|
  --------------------
> [NET] No such file found at server: Spalt-0p5mm_2020-08-13_O2env-0p1Proz_Volt-6kV_Freq-10kHz_HVpw-50us_Flanke-SF_N2-299sccm_O2-0p3sccm_NrImages-25_Entl-EE_t0-0ns_Gate-250ns_Gain-200.npy
> [NET] Attempting to connect...
> [NET] Listening to incoming data
> [NET] Connected to server
> [NET] No such file found at server: Spalt-0p5mm_2020-08-31_O2env-2Proz_Volt-8kV_Freq-10kHz_HVpw-0p2us_Flanke-FF_N2-294sccm_O2-6sccm_NrImages-25_Entl-x_Akku-1000_t0-360ns_Gate-250ns_Gain-0.npy
> [NET] No such file found at server: Spalt-1mm_2020-12-15_O2env-0p1Proz_Volt-10kV_Freq-0p5kHz_HVpw-1us_Flanke-SF_N2-299sccm_O2-0p3sccm_NrImages-100_Entl-EE_t0-0ns_Gate-500ns_Gain-200_MFIIc_fvar_sync.npy
> [NET] No such file found at server: Spalt-1mm_2020-12-15_O2env-0p1Proz_Volt-10kV_Freq-10kHz_HVpw-50us_Flanke-SF_N2-299sccm_O2-0p3sccm_Akku-1000_t0-0ns_Gate-500ns_Gain-0_MFIIc_fvar.npy
> [NET] No such file found at server: Spalt-1mm_2020-11-25_O2env-2Proz_Volt-10kV_Freq-10kHz_HVpw-1us_Flanke-FF_N2-294sccm_O2-6sccm_NrImages-25_Entl-EE_t0-1100ns_Gate-500ns_Gain-200_MFIIc.npy
> ------Dataset-------
  |8bit         False|
  |grayscale     True|
  |max. RAM       1.0|
  |Size-ratio     1.0|
  |Subset-ratio   1.0|
  |Size (MB)    0.335|
  --------------------
> [NET] No such file found at server: Spalt-1mm_2020-12-16_O2env-20Proz_Volt-10kV_Freq-5kHz_HVpw-100us_Flanke-FF_N2-240sccm_O2-60sccm_Akku-1000_t0-100190ns_Gate-2ns_Gain-50_texp-0p2s_MFIIc_Schritte-50_Sequenz_fvar_plus1nsSchritt.npy
> [NET] No such file found at server: Spalt-1mm_2020-11-26_O2env-20Proz_Volt-10kV_Freq-10kHz_HVpw-50us_Flanke-SF_N2-240sccm_O2-60sccm_NrImages-100_Entl-EE_t0-150ns_Gate-200ns_Gain-200_MFIIc_sync_set-a.npy
> ------Dataset-------
  |8bit         False|
  |grayscale     True|
  |max. RAM       1.0|
  |Size-ratio     1.0|
  |Subset-ratio   1.0|
  |Size (MB)    8.105|
  --------------------
> [NET] No such file found at server: Spalt-1mm_2021-07-14_O2env-0p1Proz_Volt-8kV_Freq-10kHz_HVpw-1us_Flanke-FF_N2-299sccm_O2-0p3sccm_NrImages-25_Entl-EE_t0-1100ns_Gate-500ns_Gain-200_MFIIc_Uvar.npy
> ------Dataset-------
  |8bit         False|
  |grayscale     True|
  |max. RAM       1.0|
  |Size-ratio     1.0|
  |Subset-ratio   1.0|
  |Size (MB)    0.322|
  --------------------
> [NET] Connected to server
> [NET] Connected to server
> [NET] Connected to server

**Comment by PiMaV** [comment]
seems to work now
