### ISSUE TITLE
For V1.2 FINAL

### ISSUE THREAD

**Issue by PiMaV** [PiMaV/BLITZ#33]
**Preface:**
This should be implemented before the final release of V1.2.
I've introduced:
- (LP) for "low priority"
- (4D) for "for discussion"

### General Functionality

- [x] 1. **Drag & Drop**: Store the folder path when images are loaded. The next time "Open Folder" is clicked, it should open the last used folder.
- [x] 2. **Busy/Loading Window**: Display the "Busy / Loading" window more frequently, such as during "Undo" from "Crop" or "Apply" with a mask. (LP)
- [x] 3. **ROI Modification**: Allow ROI to be user-modifiable, similar to the measurement tool, to create non-rectangular polygon areas. (LP)
- [x] 4. **Links in Menu Bar**: Add links to GITHUB and INP in the menu bar. (4D) (LP)
- [x] 5. **Version Display Bug**: Fix the bug where the title bar shows version 1.1.0 instead of the current 1.2.0.
- [x] 6. **Save Settings Per Folder**: Create a hidden file to save settings (metadata) such as crop region, mask, LUT, etc., per folder or file when opened for the first time. (4D) (LP)
- [x] 7. **Masking**: Implement a feature to load a binary/BW image of the same size for masking. This would be a sub-point of "mask". (LP)
- [ ] #53
- [ ] 9. **Walkthrough Update**: Update the walkthrough once V1.2 FINAL is released.
- [x] 10. **Red Dot**: The intersection of the crosshair should also be visible in the H & V plots as a red line.
- [x] 11. **Export Waitbar**: Display a "Waitbar" during image export (in case huge imagesets are exported).

### LUT:

- [x] - **Manual Scaling**: Deactivate "Auto-fit" checkbox when scaling LUT manually.
- [x] - **Autofit Deactivation**: Ensure "Autofit" is deactivated when using "Reduction". If activated, it should be applied. Currently, mean, min, and max share the same limits, even when auto-fit is active. (LP)

#### Crop:

- [x] - **Rename**: Change "Crop" to "Timeline Cropping".
- [x] - **Keep Original**: Rename "Keep Original" to "Keep All Data in RAM". Tooltip: "Keep Full Dataset in RAM for faster reloading".
- [x] - **Undo Handling**: Instead of showing an error when clicking "Undo" without "Keep Original" checked, reload the dataset from the HDD using the stored file path as mentioned in General Functionality point 1.

#### Reduction:

- [x] - **Rename**: Change "Reduction" to "Image Aggregation". Tooltip: "Temporal Dimensionality Reduction: Create summary images by aggregating pixel values (e.g., minimum, maximum, mean, standard deviation) across a time series of images."

#### Normalization:

- [x] - **Selection Simplification**: Limit selection to either Range or Background for simplicity. Atm one can selected both, but it doesnt work. (LP) 

### Tools:

- [x] - **Unit Display**: Replace "mm" with "au". Update the checkbox to "Display in 'au' (Arbitrary unit)".
- [x] - **Spinner Box**: Ensure spinners can handle at least 5 digits. Consider stacking boxes below each other to save space.
- [x] - **Floating Point Support**: Allow floats below 1, e.g., 100 px = 0.001 m. (LP)
- [x] - **Measurement Tool Info Box**:
  - Show sum of all segment lengths.
  - Calculate and show area.
  - Display bounding rectangle with length and width. (LP)
  - Ensure both measurements are available in pixels or au.

**Comment by irkri** [comment]
Additionally:
- Fixed Masking: Can be now applied together with any operation besides "View-related" (flip, transpose) things.
- Normalization: ... over time range, sliding window or background can all be applied at the same time.

**Comment by PiMaV** [comment]
Link to Newsletter:
https://mipse.umich.edu/iltpc_newsletter36.php#research
then scroll down.

heres also the DOI for the dataset

**Comment by PiMaV** [comment]
[] We should reanable Dicom images

**Comment by irkri** [comment]
We can now save settings per project. You can drag and drop ini files, which remember the data path and most settings.

**Comment by irkri** [comment]
Autofit function for the LUT has been changed:
- do not fit levels if masking
- do not fit levels if cropping data (or undo cropping)
- do not fit levels if aggregating (mean, max, ...)
- fit levels if loading new data

It is now possible to fit levels via button press.

**Comment by irkri** [comment]
- issue for DOI is up for discussion
- walkthrough will be updated in future versions

I am closing this issue as most important features are already supported in newer versions of BLITZ.

**Comment by PiMaV** [comment]
> We can now save settings per project. You can drag and drop ini files, which remember the data path and most settings.

this is OK. Yet we should think about some kind of "auto-save-load" settings funciton. That means, if the checkbox is active, we look for a settings file in the folder and load it (with LUT. Mask, maybe even Normalization settings and apply) with the data, as well as save it in the folder when something is changed
