### ISSUE TITLE
New Features - Time - Normalization

### ISSUE THREAD

**Issue by PiMaV** [PiMaV/BLITZ#35]
- [x] - Bluring of the "used" image
- [x] - alpha (this could already be the same as  = 0-100%)
- [x] - time shift ( so a mean range can "lag" some frames behind) 
   i.e: Range of background is "3" and t_shift is "2" -> so image 27 is subtracted by the mean of images 23:25 (=27- 2 - (2:0)

**Comment by irkri** [comment]
- I don't know what you mean with "blurring". A gaussian kernel applied over the image?
- I think the `alpha` you mean is the spinbox we already have. Maybe the tooltip helps?
- This is now implemented and should work as intended.

**Comment by PiMaV** [comment]
- Yepp . Gaussian. Just starting with 3 and odd. thats it
- lets skip 2 for now
