### ISSUE TITLE
small bug in bounding_rect

### ISSUE THREAD

**Issue by PiMaV** [PiMaV/BLITZ#40]
Got his while playing with an image:

Traceback (most recent call last):
  File "C:\PYTHON\BLITZ\blitz\layout\widgets.py", line 195, in update_bounding_rect
    left = min([p[1].x() for p in pos])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: min() arg is an empty sequence

**Comment by irkri** [comment]
This is fixed, we now check if the sequence in question is empty before taking min or max.

**Comment by PiMaV** [comment]
thus done
