### ISSUE TITLE
Numbers are gone

### ISSUE THREAD

**Issue by PiMaV** [PiMaV/BLITZ#42]
On noisy data, the three numbers, giving back the pixel values are not visible anymore...
(they drop below y=0) 

![image](https://github.com/user-attachments/assets/086b182a-788b-4540-a7cc-a6e1ca95658a)

**Comment by PiMaV** [comment]
Changing 

anchor=(.5, 1),

would do it. However, we need to take care of:

**Comment by irkri** [comment]
This is not a problem of the indices specifically. Sometimes the plots just do not auto-fit when the y-range changes. This seems like a bigger problem to fix, but a minor bug. I don't think its worth fixing right now. Zooming out manually is always possible, or `right-click  -> View all`.

**Comment by PiMaV** [comment]
Agreed not to fix in general.
-> Please adapt the "hotfix" with the slightly changed anchors per number

**Comment by irkri** [comment]
The indices then might cross the plotted lines. But I changed the anchor now (also adapted for the vertical plot).
