### ISSUE TITLE
Full RosEE Implemention

### ISSUE THREAD

**Issue by PiMaV** [PiMaV/BLITZ#43]
- [x] show isocurves (maybe even with draggable lines)
- [x] show points for each horz. line

**Comment by irkri** [comment]
- The isocurves are currently our horizontal and vertical movable lines. Adding another draggable line to BLITZ maybe does not fit in our setting. Which plot (horizontal, vertical) should then visualize RoSEE's fluctuation sum?
- What points do you mean?

**Comment by PiMaV** [comment]
to be discussed in person.

**Comment by irkri** [comment]
the points will be done with Version 1.2.2; coming out soon
