### ISSUE TITLE
improved default folder settings

### ISSUE THREAD

**Issue by PiMaV** [PiMaV/BLITZ#56]
We should think about some kind of "auto-save-load" settings funciton. That means, if the checkbox is active, we look for a settings file in the folder and load it (with LUT, Mask, maybe even Normalization settings and apply) with the data, as well as save it in the folder when something is changed on the fly

**Comment by PiMaV** [comment]
there might have been a misunderstanding:
I thought it would be a good idea to have an ini - file per folder. So to load and reapply folder settings each time im loading a folder; not from the "master" ini, but an ini file that is within the iamge folder and just has the image + loading related parameters within the file

**Comment by irkri** [comment]
I now understand. The last commit did fix it. If the checkbox is checked, we now save ini files at the loaded dataset locations and update all settings with it. There are also options to save the ini file manually under Project->Save or Project->Save as.

**Comment by irkri** [comment]
There again was a slight misunderstanding, but it should be fixed now.
Before the last commit, you had to explicitly drag & drop the ini file, not the corresponding folder/file. I now changed it so that the ini file automatically gets loaded when the folder/file is loaded.

**Comment by PiMaV** [comment]
Also seems to be fixed!
