### ISSUE TITLE
Isolines sticky 

### ISSUE THREAD

**Issue by PiMaV** [PiMaV/BLITZ#64]
Isolines are persistent once active, or they are marked active, but are actually not. 
Gets weirder when drag drop new image

**Comment by irkri** [comment]
I currently do not see any problem. What do you mean with "active"?
Drag and dropping new data should disable RoSEE. Maybe the last small commit fixed it.

**Comment by PiMaV** [comment]
cant reproduce. Probably fixed as you suggested
